os: windows
language: shell
branches:
  only:
  - master
script:
- choco pack cerebro-es\\cerebro-es.nuspec
after_script:
- choco apikey --key $CHOCOAPIKEY --source https://push.chocolatey.org/
- choco push
